### ISSUE TITLE
is there anyway to control what to cache?

### ISSUE THREAD

**Issue by peshanghiwa** [ziaadini/nuxt-perfect-cache#10]
Is there any way to control the components on the screen that are being cached?
like i don't want every data on the page to be cached.

for example in the following code i have two components, component one is visible to everyone and component 2 is visible to only authenticated users, i want to only cache component one if i am even authenticated.
is that possible in anyway?
`<div><component1 auth="false" /><component2 auth="true" /></div>`
and please can you create a real example of using nuxt-perfect-cache and provide it here on github to see how is it work?

**Comment by ziaadini** [comment]
there is no way to cache a part of page because it's html rendered from nuxt not components.
about your problem you most take care of it in client side not server side you can change credential as soon as your page mounted.
also check this security warning i have wrote here : 
https://github.com/ziaadini/nuxt-perfect-cache#caveat

**Comment by peshanghiwa** [comment]
> there is no way to cache a part of page because it's html rendered from nuxt not components.
> about your problem you most take care of it in client side not server side you can change credential as soon as your page mounted.
> also check this security warning i have wrote here :
> https://github.com/ziaadini/nuxt-perfect-cache#caveat

Great, i added auth related data to client side and it worked.
