### ISSUE TITLE
Can you do a demo on API caching and page caching

### ISSUE THREAD

**Issue by 710427941** [ziaadini/nuxt-perfect-cache#16]
Now that the API is cached to Redis, app.$cacheFetch will continue to request the interface next time. Could you please teach us how to use this location

**Comment by ziaadini** [comment]
it's well documented what is the problem are you facing in?
`cacheFetch method will check if the process is in the server then check key in redis if key exist return data from redis if not call your callback as normal this method useful for consistent requests such as menu`

it's clear if user navigate in client side it will request to the api as normal and if process is in the server it will check if data exist in redis or not, if exist then there is no need to send request any more, then return redis data, otherwise it will request to the api and cache once again.

**Comment by 710427941** [comment]
Thank you very much for your answer. I got the information at the server and have successfully processed the data
